### PR TITLE
FIx incorrect barrier when resolving the depth attachment on writebac…

### LINKED ISSUE #235: Incorrect barrier when resolving the depth attachment on writeback in MSAA sample.
When the "Best Practices" or "Synchronization(Alpha) " layer is enabled, The `MSAA` sample show the WAW error if enable resolve the depth attachment on writeback:
`SYNC-HAZARD-WRITE_AFTER_WRITE: Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x7dd77f00000057bb, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfdf9f5e1 | vkCmdPipelineBarrier: Hazard WRITE_AFTER_WRITE for image barrier 0 VkImage 0x7dd77f00000057bb[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 51, reset_no: 141).`

### PR DESCRIPTION
**Pull request by congyue1977**
…k in MSAA sample

## Description

The resolving depth occurs in the COLOR_ATTACHMENT_OUT stage, not in the EARLY\LATE_FRAGMENT_TESTS stage
and the corresponding access mask is COLOR_ATTACHMENT_WRITE_BIT, not DEPTH_STENCIL_ATTACHMENT_WRITE_BIT.

Fixes #235 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

File: framework/rendering/postprocessing_renderpass.cpp [hunk 1]
```diff
@@ -429,7 +446,13 @@ void PostProcessingRenderPass::prepare_draw(CommandBuffer &command_buffer, Rende
 			if (const uint32_t *sampled_attachment = it.second.get_target_attachment())
 			{
 				auto *image_rt = it.second.get_render_target();
-				sampled_attachments.insert({image_rt, *sampled_attachment});
+				auto  packed_sampled_attachment = *sampled_attachment;
+
+				// pack sampled attachment
+				if (it.second.is_depth_resolve())
+					packed_sampled_attachment |= 1 << 31;
```
Comment (garyjsweet) [inline framework/rendering/postprocessing_renderpass.cpp]: I'm not a huge fan of hijacking bits to convey extra information, but if we have to could we use some named constants for the bit and the mask rather than magic numbers (0x7FFFFFFF, 0x80000000, 1 << 31)?

Comment (congyue1977) [reply framework/rendering/postprocessing_renderpass.cpp]: > I'm not a huge fan of hijacking bits to convey extra information, but if we have to could we use some named constants for the bit and the mask rather than magic numbers (0x7FFFFFFF, 0x80000000, 1 << 31)?

Done.

**Review by gary-sweet — APPROVED** [review]

File: framework/rendering/postprocessing_renderpass.cpp [hunk 2]
```diff
@@ -429,7 +449,13 @@ void PostProcessingRenderPass::prepare_draw(CommandBuffer &command_buffer, Rende
 			if (const uint32_t *sampled_attachment = it.second.get_target_attachment())
 			{
 				auto *image_rt = it.second.get_render_target();
-				sampled_attachments.insert({image_rt, *sampled_attachment});
+				auto  packed_sampled_attachment = *sampled_attachment;
+
+				// pack sampled attachment
+				if (it.second.is_depth_resolve())
```
Comment (JoseEmilio-ARM) [inline framework/rendering/postprocessing_renderpass.cpp:455]: (code-style) add braces even if single-line statement

**Review by JoseEmilio-ARM — COMMENTED** [review]
LGTM, thanks!

File: framework/rendering/postprocessing_renderpass.cpp (hunk 2 above)
Comment (JoseEmilio-ARM) [reply framework/rendering/postprocessing_renderpass.cpp:455]: just checked the code-style guide and it does allow for this, approving https://google.github.io/styleguide/cppguide.html#Conditionals

**Review by JoseEmilio-ARM — APPROVED** [review]

**Comment by marty-johnson59** [comment]
Can we get one more review on this one so we can merge?  Thanks!
@aurolou, @ZandroFargnoli, @mattruschnv, @AlejandroCosin, @carlosadcq, @r-potter, @wasimabbas-arm

**Review by aurolou — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]
