### PR TITLE
Set color blend equation state in shader object sample (validation fix)

### LINKED ISSUE #917: Validation issues with shader object example
With the latest SDK, the shader object sample will display new validation errors that needs to be fixed (VUID-vkCmdDrawIndexed-rasterizerDiscardEnable-09418).

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This PR sets the color blend equation state as required per the spec. This fixes a validation error in the sample that shows up with the latest SDK. It also fixes a few warnings due to uninitialized values.

Fixes #917

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

**Review by asuessenbach — DISMISSED** [review]

**Comment by SaschaWillems** [comment]
@tomadamatkinson : This also fails with clang format checks :(

**Review by asuessenbach — DISMISSED** [review]

File: samples/extensions/shader_object/shader_object.cpp [hunk 1]
```diff
@@ -1,6 +1,11 @@
 /*
+<<<<<<< HEAD
+ * Copyright 2023-2024 Nintendo
+ * Copyright 2023-2024, Sascha Willems
+=======
  * Copyright 2023-2024-2024 Nintendo
  * Copyright 2023-2024-2024, Sascha Willems
+>>>>>>> main
```
Comment (gary-sweet) [inline samples/extensions/shader_object/shader_object.cpp]: Looks like there are merge conflict markers left in this file

**Review by gary-sweet — CHANGES_REQUESTED** [review]

File: samples/extensions/shader_object/shader_object.cpp (hunk 1 above)
Comment (SaschaWillems) [reply samples/extensions/shader_object/shader_object.cpp]: Sorry, my bad. Didn't realize this and it compiled fine due to being in a comment. Should be fixed by now :)

**Review by gary-sweet — APPROVED** [review]

**Review by asuessenbach — APPROVED** [review]
