### PR TITLE
Fix acquiring image

### LINKED ISSUE #337: Crash after fullscreen
When I press CTRL+F (Toggle fullscreen mode) on my arch linux desktop running GNOME 40, it fakes the fullscreen. The window is maximized and the top bar is hidden. When I try that on the app, it crashes.

In the file framework/rendering/render_context.cpp in the function RenderContext::begin_frame(), we acquire the next image. If the result is suboptimal or out of date, we check for updated extend and update the swapchain. Then back in begin_frame, we acquire the next image again and check the result. If it isn't successful, the frame is reset and we return. That than triggers an assert that the frame isn't ready.

https://github.com/KhronosGroup/Vulkan-Samples/blob/fd4dc37e5ce272a5ba0b34b5a8e259090231e12e/framework/rendering/render_context.cpp#L340

System specs (inxi -F):

```
System:
  Host: arch Kernel: 5.13.13-arch1-1 x86_64 bits: 64 Desktop: GNOME 40.4 
  Distro: Arch Linux 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME H270M-PLUS v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 0320 
  date: 11/22/2016 
CPU:
  Info: Quad Core model: Intel Core i7-7700 bits: 64 type: MT MCP cache: 
  L2: 8 MiB 
  Speed: 800 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 801 6: 801 7: 800 8: 800 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 470.63.01 
  Device-2: Sonix USB 2.0 Camera type: USB driver: snd-usb-audio,uvcvideo 
  Display: x11 server: X.org 1.20.13 driver: loaded: nvidia 
  unloaded: modesetting resolution: <missing: xdpyinfo> 
  Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:
  Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel 
  Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel 
  Device-3: Sonix USB 2.0 Camera type: USB driver: snd-usb-audio,uvcvideo 
  Sound Server-1: ALSA v: k5.13.13-arch1-1 running: yes 
  Sound Server-2: PulseAudio v: 15.0 running: yes 
  Sound Server-3: PipeWire v: 0.3.34 running: yes 
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e 
  IF: enp0s31f6 state: up speed: 100 Mbps duplex: full 
  mac: 2c:4d:54:56:d2:66 
Drives:
  Local Storage: total: 3.89 TiB used: 73.57 GiB (1.8%) 
  ID-1: /dev/sda vendor: Crucial model: CT275MX300SSD1 size: 256.17 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD40EFRX-68N32N0 
  size: 3.64 TiB 
Partition:
  ID-1: / size: 48.87 GiB used: 30.16 GiB (61.7%) fs: ext4 dev: /dev/sda3 
  ID-2: /home size: 687.94 GiB used: 43.41 GiB (6.3%) fs: ext4 
  dev: /dev/sdb3 
Swap:
  ID-1: swap-1 type: file size: 1024 MiB used: 116 MiB (11.3%) 
  file: /swapfile 
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 287 Uptime: 1h 40m Memory: 15.57 GiB used: 5.57 GiB (35.8%) 
  Shell: fish inxi: 3.3.06 
```

### PR DESCRIPTION
**Pull request by lukaprsina**
Vulkan crashes on arch linux running GNOME 40 when going fullscreen. Issue #337

I read issue #305 after I submitted mine. 

Fixes #337 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

File: framework/rendering/render_context.cpp [hunk 1]
```diff
@@ -335,14 +366,15 @@ void RenderContext::begin_frame()
...
-			handle_surface_changes();
+			bool swapchain_updated = handle_surface_changes(result == VK_ERROR_OUT_OF_DATE_KHR);
 
 			result = swapchain->acquire_next_image(active_frame_index, acquired_semaphore, VK_NULL_HANDLE);
 		}
 
 		if (result != VK_SUCCESS)
 		{
 			prev_frame.reset();
+			assert(false);
```
Comment (SaschaWillems) [inline framework/rendering/render_context.cpp]: I'm not sure if we want to have a fixed assert in here. Wouldn't that potentially break existing error handling? Or at least use std::throw instead of an assert like the rest of the code.

File: framework/rendering/render_context.cpp [hunk 2]
```diff
@@ -285,6 +291,31 @@ CommandBuffer &RenderContext::begin(CommandBuffer::ResetMode reset_mode)
 		throw std::runtime_error("Couldn't begin frame");
 	}
 
+	static VkExtent2D previous1;
```
Comment (SaschaWillems) [inline framework/rendering/render_context.cpp]: Is there are more consistent way (in terms of how the framework is currently working) of doing this without static variables? If not, this code should have some comments to explain how this works and why this code is in place.

Comment (lukaprsina) [reply framework/rendering/render_context.cpp]: I'm sorry for not making myself clear.

This commit was just for logging the swapchain extent for the issue https://github.com/KhronosGroup/Vulkan-Samples/issues/337#issuecomment-916984745.

The suggested commit is https://github.com/KhronosGroup/Vulkan-Samples/pull/338/commits/c5b957a79715020054a4a81ecfd6bc285dc50d54.

File: framework/core/swapchain.cpp [hunk 3]
```diff
@@ -403,8 +403,9 @@ void Swapchain::create()
 	properties.surface_format = choose_surface_format(properties.surface_format, surface_formats, surface_format_priority_list);
 
 	VkSwapchainCreateInfoKHR create_info{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};
-	create_info.minImageCount    = properties.image_count;
-	create_info.imageExtent      = properties.extent;
+	create_info.minImageCount = properties.image_count;
+	create_info.imageExtent   = properties.extent;
+	LOGW("SW::CREATE: {}, {};", properties.extent.width, properties.extent.height);
```
Comment (gpx1000) [inline framework/core/swapchain.cpp]: Now that we've debugged this it's safe to remove the extra logs

**Review by gpx1000 — COMMENTED** [review]
LGTM; let's remove the logs and I'll give an approval.

File: framework/rendering/render_context.cpp [hunk 4]
```diff
@@ -253,22 +253,28 @@ void RenderContext::handle_surface_changes()
...
+		LOGW("RC::HANDLE_SURFACE_CHANGES current: {}, {};", surface_properties.currentExtent.width, surface_properties.currentExtent.height);
+		LOGW("RC::HANDLE_SURFACE_CHANGES surface_extent: {}, {};", surface_extent.width, surface_extent.height);
 		// Recreate swapchain
 		device.wait_idle();
 
 		update_swapchain(surface_properties.currentExtent, pre_transform);
 
 		surface_extent = surface_properties.currentExtent;
+
+		return true;
```
Comment (TomAtkinsonArm) [inline framework/rendering/render_context.cpp:274]: Return isn't needed here

**Review by TomAtkinsonArm — CHANGES_REQUESTED** [review]
LGTM. Logging can be removed as pointed out by Steve, ~small nit pick from me~ and then I will approve

> small nit pick from me

Apologies, had another look over and I was wrong. Just logging to remove and this is good to go

**Comment by lukaprsina** [comment]
I have read the issue https://github.com/KhronosGroup/Vulkan-Samples/issues/250 created by @danilw. He crashed the app just by resizing. I also tried resizing the window for about a minute on my branch and the official branch, but it did not crash for me. Can't reproduce.

P.S. I must have force pushed the wrong commit. Log calls are now removed.

**Review by SaschaWillems — DISMISSED** [review]

**Review by gpx1000 — DISMISSED** [review]
LGTM

**Review by TomAtkinsonArm — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
Hi @lukaprsina, looks like were close here.  Can you update the copyright here so we can pass all the checks?  Need that done before I can merge.  Thanks!
