### PR TITLE
Fix UI scaling and mouse interaction on retina displays

### LINKED ISSUE #76: Mouse interaction does not work properly on Mac Retina displays
The logic in gui.cpp takes into account the physical size of the monitor in order to scale content (via `dpi_factor`) however, it does not handle a disparity between the window coordinate system used for input events and the framebuffer surface pixel coordinate system.  

On retina mac displays input events come in at half the resolution of the actual screen.  This can be be seen in a disparity between the values returned by `glfwGetWindowSize` and `glfwGetFramebufferSize`.  In GLFW 3.3 and up this is available from the convenience function `glfwGetWindowContentScale`.  

See the behavior here...
ezgif-7-c56ed2a1f02a

### PR DESCRIPTION
**Pull request by jherico**
## Description

Closes #76 

## General Checklist:

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [X] My changes do not add any new compiler warnings
- [X] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [X] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

File: framework/gui.cpp [hunk 1]
```diff
@@ -93,11 +94,16 @@ const ImGuiWindowFlags Gui::options_flags = Gui::common_flags;
 
 const ImGuiWindowFlags Gui::info_flags = Gui::common_flags | ImGuiWindowFlags_NoInputs;
 
-Gui::Gui(VulkanSample &sample_, const float dpi_factor, const float font_size, bool explicit_update) :
+Gui::Gui(VulkanSample &sample_, const std::unique_ptr<Window> &window, const float font_size, bool explicit_update) :
```
Comment (ZandroFargnoli) [inline framework/gui.cpp]: Why are we passing a pointer? When would we want the window to be null? This should be a const reference IMO

File: framework/gui.cpp [hunk 2]
```diff
@@ -93,11 +94,16 @@ const ImGuiWindowFlags Gui::options_flags = Gui::common_flags;
...
     sample{sample_},
-    dpi_factor{dpi_factor},
     explicit_update{explicit_update}
 {
+	if (window)
+	{
+		retina_factor = window->get_retina_factor();
```
Comment (ZandroFargnoli) [inline framework/gui.cpp]: If we pass the reference to the window in the constructor, it means it has to be initialised. We can then initialise these values up inside the member initialisation braces

File: framework/platform/glfw_window.h [hunk 3]
```diff
@@ -44,6 +44,8 @@ class GlfwWindow : public Window
 
 	float get_dpi_factor() const override;
 
+	float get_retina_factor() const override;
```
Comment (ZandroFargnoli) [inline framework/platform/glfw_window.h]: `Retina` is an Apple concept/brand. This should really just be `get_x_content_scale` as this doesn't necessarily pertain to only macOS, but all platforms.

File: framework/gui.h [hunk 4]
```diff
@@ -470,6 +472,9 @@ class Gui
 	/// Scale factor to apply to the size of gui elements (expressed in dp)
 	float dpi_factor{1.0f};
 
+	///  Scale factor to apply due to a difference between the window and GL pixel sizes
+	float retina_factor{1.0f};
```
Comment (ZandroFargnoli) [inline framework/gui.h]: Rename to `x_content_scale_factor`

File: framework/platform/platform.h [hunk 5]
```diff
@@ -100,6 +100,11 @@ class Platform
 
 	Window &get_window() const;
 
+	const std::unique_ptr<Window> &get_window_ptr() const
```
Comment (ZandroFargnoli) [inline framework/platform/platform.h]: Why does this function need to be added? We already have `Window &get_window() const;`, which invalidates the checklist item `I have used existing framework/helper functions where possible`

Comment (ZandroFargnoli) [reply framework/platform/platform.h]: If you have an argument for adding this, can we place implementation inside the `.cpp`

File: framework/platform/window.h [hunk 6]
```diff
@@ -67,6 +67,14 @@ class Window
 	 */
 	virtual float get_dpi_factor() const = 0;
 
+	/**
+     * @return The scale factor for systems with heterogenous window and pixel coordinates
+     */
+	virtual float get_retina_factor() const
```
Comment (ZandroFargnoli) [inline framework/platform/window.h]: Can implementation be kept inside the `.cpp` file?

**Review by ZandroFargnoli — CHANGES_REQUESTED** [review]
Make sure you also modify `bldsys/cmake/template/sample/sample.cpp.in` so when people wish to generate a new sample it doesn't come with compilation errors out the box

File: framework/platform/window.h [hunk 7]
```diff
@@ -67,6 +67,14 @@ class Window
 	 */
 	virtual float get_dpi_factor() const = 0;
 
+	/**
+     * @return The scale factor for systems with heterogenous window and pixel coordinates
```
Comment (ZandroFargnoli) [inline framework/platform/window.h]: `heterogenous` -> `heterogeneous`

File: framework/platform/window.h (hunk 6 above)
Comment (ZandroFargnoli) [reply framework/platform/window.h]: And typo `heterogeneous` (not `heterogenous`)

File: framework/gui.cpp (hunk 1 above)
Comment (jherico) [reply framework/gui.cpp]: I was trying to reproduce the behavior of the old signature, which allowed everything after `sample_` to be an optional parameter, but given the current usage pattern, I agree that passing a const ref is better.  will fix.

File: framework/gui.cpp (hunk 2 above)
Comment (jherico) [reply framework/gui.cpp]: will fix

File: framework/platform/glfw_window.h (hunk 3 above)
Comment (jherico) [reply framework/platform/glfw_window.h]: I've changed it to `get_content_scale_factor` because the fact that it's the x factor is part of an implementation detail inside glfw that supports non-uniform scaling (and thus non-square pixels).  I'd rather either support non-uniform scale all the way through (which would require further changes to `Gui` or just assume uniform scaling for now.

File: framework/gui.h (hunk 4 above)
Comment (jherico) [reply framework/gui.h]: changed to `content_scale_facter` per above.

File: framework/platform/platform.h (hunk 5 above)
Comment (jherico) [reply framework/platform/platform.h]: will remove

File: framework/platform/window.h (hunk 6 above)
Comment (jherico) [reply framework/platform/window.h]: will fix

File: framework/platform/window.h (hunk 7 above)
Comment (jherico) [reply framework/platform/window.h]: will fix

File: framework/platform/glfw_window.h (hunk 3 above)
Comment (ZandroFargnoli) [reply framework/platform/glfw_window.h]: Okay, I agree with this

**Review by ZandroFargnoli — APPROVED** [review]
LGTM
