### PR TITLE
Fix: Swapchain recreation - validation errors

### LINKED ISSUE #1287: swapchain_recreation missing swapchainMaintenance1 feature
The latest Validation (future 1.4.309 SDK) I get

```
Validation Error: [ VUID-VkSwapchainCreateInfoKHR-swapchainMaintenance1-10157 ] | MessageID = 0xedce379e
vkCreateSwapchainKHR(): pCreateInfo->flags is VK_SWAPCHAIN_CREATE_DEFERRED_MEMORY_ALLOCATION_BIT_EXT, but swapchainMaintenance1 is not enabled.
The Vulkan spec states: If the swapchainMaintenance1 feature is not enabled, then flags must not include VK_SWAPCHAIN_CREATE_DEFERRED_MEMORY_ALLOCATION_BIT_EXT (https://docs.vulkan.org/spec/latest/chapters/VK_KHR_surface/wsi.html#VUID-VkSwapchainCreateInfoKHR-swapchainMaintenance1-10157)
```

for the `swapchain_recreation` example

Simple fix is to just enable the `swapchainMaintenance1` feature along with the extension it already provides

### PR DESCRIPTION
**Pull request by jeroenbakker-atmind**
## Description

Swapchain recreation sample uses VK_EXT_swapchain_maintenance1, but doesn't activate its features causing several validation errors. This PR doesn't fix all validation errors, only the default ones. The other will be solved separately as
they are unrelated to enabling feature.

Tested on
```
Operating system: macOS-15.3.2-x86_64-i386-64bit 64 Bits
Graphics card: Apple M2 1.2
VulkanSDK: 1.4.309.0
```

Fixes: #1287

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

 If this PR contains framework changes:
 - [x] I did a full batch run using the `batch` command line argument to make sure all samples still work properly

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the readme of the folder that the sample belongs to [e.g. api samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

File: samples/api/swapchain_recreation/swapchain_recreation.cpp [hunk 1]
```diff
@@ -900,6 +900,7 @@ SwapchainRecreation::SwapchainRecreation()
 		add_instance_extension(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME, true);
 		add_instance_extension(VK_EXT_SURFACE_MAINTENANCE_1_EXTENSION_NAME, true);
 		add_device_extension(VK_EXT_SWAPCHAIN_MAINTENANCE_1_EXTENSION_NAME, true);
+		has_maintenance1 = true;
```
Comment (jeroenbakker-atmind) [inline samples/api/swapchain_recreation/swapchain_recreation.cpp]: It was nicer to include a use_maintenance1, but the documentation of has_maintenance1 attribute already covers the same intent. Let me know if this is fine.

**Comment by SaschaWillems** [comment]
I'm not sure about this. `VK_EXT_swapchain_maintenance1` is optional for this sample, and forcing has_maintenance1 to `true´ will break the sample when that extension is not available.

**Comment by jeroenbakker-atmind** [comment]
the has_maintenance1 will be disabled when not supported or forced disable in create_device.

```cpp
std::unique_ptr<vkb::Device> SwapchainRecreation::create_device(vkb::PhysicalDevice &gpu)
{
	std::unique_ptr<vkb::Device> device = vkb::VulkanSampleC::create_device(gpu);

	has_maintenance1 = get_instance().is_enabled(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME) &&
	                   get_instance().is_enabled(VK_EXT_SURFACE_MAINTENANCE_1_EXTENSION_NAME) &&
	                   device->is_enabled(VK_EXT_SWAPCHAIN_MAINTENANCE_1_EXTENSION_NAME);
```

We can clarify this by separating the `has_maintenace1` as suggested in the review comments. (use_maintenance1/force_disable_maintenance1). 

The readability of this sample can also be improved. Perhaps separating it into two samples (`swapchain_recreation` and `swapchain_recreation_mainteance1`) can improve it.

**Comment by jeroenbakker-atmind** [comment]
Discussed during meeting

- Make a new PR to see if separating the sample in two would improve the readability (#1329)
- We can see if we want to merge this or the other PR
- During the meeting we also discussed using compiler directives. However this is just replacing the if statement with ifdefs and might not solve the readability.

**Comment by jeroenbakker-atmind** [comment]
After doing the experiment I prefer to keep it in a single sample, but introduce a new attribute.
- Code duplication is much more then initially expected.
- compile directives could help out. as IDEs typically make them distinguishable.

**Comment by jeroenbakker-atmind** [comment]
experiment didn't solve what I had in mind and has been closed. So this PR can be reviewed for landing. The variable has been split for better readability of the flow.

**Review by SaschaWillems — DISMISSED** [review]

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]
