### PR TITLE
Raytracing extended validation fixes

### LINKED ISSUE #389: Raytracing extended pool size
Maybe I'm missing something, but I think there is an issue with the function
RaytracingExtended::create_descriptor_sets() in raytracing_extended.cpp:

as far as I can tell descriptor_set is allocated from a pool with just 1 one each descriptors in VkDescriptorPoolSize, but it has 7 storage buffers, 26 textures and 1 acceleration structure.

If so, I find weird that the validation layers are not complaining about it.

### PR DESCRIPTION
**Pull request by gpx1000**
## Description

address 3 validation issues.
1.) instances were created more than once
2.) flame texture sampler wasn't destroyed
3.) memory barrier tested against top of pipeline when acceleration structure.

Fixes #389 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

File: samples/extensions/raytracing_extended/raytracing_extended.cpp [hunk 1]
```diff
@@ -872,8 +877,8 @@ void RaytracingExtended::create_descriptor_sets()
 {
 	std::vector<VkDescriptorPoolSize> pool_sizes = {
```
Comment (cforfang) [inline samples/extensions/raytracing_extended/raytracing_extended.cpp:878]: Looking at `VkDescriptorSetLayoutCreateInfo` I count:
- 1x `VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR`
- 1x `VK_DESCRIPTOR_TYPE_STORAGE_IMAGE`
- 5x `VK_DESCRIPTOR_TYPE_STORAGE_BUFFER`
- 1x `VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER`
- `raytracing_scene->imageInfos.size()`x `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`

Comment (gpx1000) [reply samples/extensions/raytracing_extended/raytracing_extended.cpp:878]: Oh, thanks right; should engage brain before commit.

**Review by JoseEmilio-ARM — APPROVED** [review]

File: samples/extensions/raytracing_extended/raytracing_extended.cpp (hunk 1 above)
Comment (cforfang) [reply samples/extensions/raytracing_extended/raytracing_extended.cpp:878]: I know the feeling :) Looks good now!

**Review by SaschaWillems — APPROVED** [review]
