### PR TITLE
Fix crash in dynamic rendering local read sample on android

### LINKED ISSUE #1277: Dynamic rendering local read sample crashes on Android
On a Google Pixel 9, the dynamic rendering local read sample crashes with a device lost. Logcat shows several validation errors:

```
[error] -710792591 - VUID-VkRenderingInfo-pNext-06080: Validation Error: [ VUID-VkRenderingInfo-pNext-06080 ] Object 0: handle = 0xb400007123b0ce80, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x4295ab0000000035, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xd5a22a71 | vkCmdBeginRenderingKHR(): pRenderingInfo->pColorAttachments[3].imageView height (720) is less than pRenderingInfo->renderArea.offset.y (0) + pRenderingInfo->renderArea.extent.height (2424).
The Vulkan spec states: If the pNext chain does not contain VkDeviceGroupRenderPassBeginInfo or its deviceRenderAreaCount member is equal to 0, the height of the imageView member of any element of pColorAttachments, pDepthAttachment, or pStencilAttachment that is not VK_NULL_HANDLE must be greater than or equal to renderArea.offset.y + renderArea.extent.height (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkRenderingInfo-pNext-06080)
[error] Error Message: Detected Vulkan error: ERROR_DEVICE_LOST
```

Since I wrote that sample I'll try to fix this.

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This fixes a crash in the dynamic rendering local read sample on Android.

Important note: In portrait mode, the sample won't be displayed in full screen. That's because the framework somehow does NOT propagate the correct screen dimensions through to the samples on Android.

Fixing that seems to be difficult, so something that should be done in a separate PR.

Fixes #1277

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

File: samples/extensions/dynamic_rendering_local_read/dynamic_rendering_local_read.cpp [hunk 1]
```diff
@@ -873,11 +873,10 @@ void DynamicRenderingLocalRead::build_command_buffers()
 		depth_attachment_info.clearValue                   = clear_values[1];
 
 		VkRenderingInfoKHR render_info   = vkb::initializers::rendering_info();
-		render_info.renderArea           = {0, 0, width, height};
+		render_info.renderArea           = {0, 0, static_cast<uint32_t>(attachment_width), static_cast<uint32_t>(attachment_height)};
```
Comment (asuessenbach) [inline samples/extensions/dynamic_rendering_local_read/dynamic_rendering_local_read.cpp:876]: Under what circumstances are `width` or `height` different from `attachment_width` or `attachment_height`?

Comment (SaschaWillems) [reply samples/extensions/dynamic_rendering_local_read/dynamic_rendering_local_read.cpp:876]: In portrait mode, see my comment above. It only applies to mobile devices.

**Review by gpx1000 — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]
