### PR TITLE
Fix synchronization in Subpasses sample

### LINKED ISSUE #455: Missing synchronization in "subpasses" sample
The sample "subpasses" has missing synchronization, which leads to display artifacts.

To reproduce enable Synchronization Validation Layers and start the sample. Then switch the Render technique between "Subpasses" and "Renderpasses". Following validation errors are printed:

```
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 32, reset_no: 1045).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 2 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 33, reset_no: 1045).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 3 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 34, reset_no: 1045).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

[info] Changing render technique
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 32, reset_no: 1050).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 2 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 33, reset_no: 1050).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 3 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 34, reset_no: 1050).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 32, reset_no: 1044).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 2 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 33, reset_no: 1044).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 3 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 34, reset_no: 1044).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 

SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5581ee092cb0, name = RP with 1 subpasses:
	[0]: 
, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4cb75b2d | vkCmdBeginRenderPass: Hazard READ_AFTER_WRITE in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_LOAD. Access info (usage: SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ, command: vkCmdPipelineBarrier, seq_no: 32, reset_no: 1042).
    Objects: 1
        [0] 0x5581ee092cb0, type: 18, name: RP with 1 subpasses:
	[0]: 
```

Note: The display artifacts are visible only when the "Subpasses" option is selected.

renderpasses
subpasses

[vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-Samples/files/8749100/vulkaninfo.txt)

### LINKED ISSUE #1197: Sample subpasses throws lots of validation errors at startup
Running the subpasses sample throws dozens of validation errors for me at startup on Windows with an RTX 4070 using the latest SDK:

```
[error] 732146062 - VUID-vkCmdDraw-None-08114: Validation Error: [ VUID-vkCmdDraw-None-08114 ] Object 0: handle = 0xa952a5000000016f, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x2ba3a98e | vkCmdDraw():  Descriptor set VkDescriptorSet 0xa952a5000000016f[] Image layout specified by vkCmdBindDescriptorSets doesn't match actual image layout at time descriptor is used. See previous error callback for specific details. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid as described by descriptor validity if they are statically used by the VkPipeline bound to the pipeline bind point used by this command and the bound VkPipeline was not created with VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-None-08114)
[error] -564812795 - VUID-VkDescriptorImageInfo-imageLayout-00344: Validation Error: [ VUID-VkDescriptorImageInfo-imageLayout-00344 ] Object 0: handle = 0x240bf4e7e30, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x59f7450000000038, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xde55a405 | vkCmdDraw():  Cannot use VkImage 0x59f7450000000038[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
```

Changing options in the UI also retriggers those.

### PR DESCRIPTION
**Pull request by JoseEmilio-ARM**
## Description

Achieve clean synchronization validation (Vulkan SDK 1.4.304.1) for the Subpasses sample

- When issuing a barrier, save the final image layout to be used consistently in other calls.
- Add correct subpass dependencies to avoid READ_AFTER_WRITE and WRITE_AFTER_WRITE hazards.
- Set correct layouts at render pass creation.
- Fix barriers in Subpasses sample.

Fixes #1197
Fixes #455
(maybe #867, #920)

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

 If this PR contains framework changes:
 - [x] I did a full batch run using the `batch` command line argument to make sure all samples still work properly

### CODE REVIEW

File: framework/core/render_pass.cpp [hunk 1]
```diff
@@ -244,23 +244,73 @@ void set_attachment_layouts(std::vector<T_SubpassDescription> &subpass_descripti
...
+
+			if (vkb::is_depth_format(attachment_descriptions[reference.attachment].format))
+			{
+				// Depth used as input
+				return true;
+			}
+		}
+	}
+
+	return false;
```
Comment (asuessenbach) [inline framework/core/render_pass.cpp:274]: Maybe a more "modern" implementation, like
```
	return std::ranges::find_if(subpass_descriptions,
	                            [&attachment_descriptions](const auto &subpass) {
		                            if (subpass.pDepthStencilAttachment != nullptr)
		                            {
			                            return true;
		                            }
		                            auto input_attachment_it =
		                                std::find_if(subpass.pInputAttachments,
		                                             subpass.pInputAttachments + subpass.inputAttachmentCount,
		                                             [&attachment_descriptions](auto const &input_attachment) { return vkb::is_depth_format(attachment_descriptions[input_attachment.attachment].format); });
		                            return std::distance(subpass.pInputAttachments, input_attachment_it) < subpass.inputAttachmentCount;
	                            }) != subpass_descriptions.end();
```

File: framework/core/render_pass.cpp [hunk 2]
```diff
@@ -244,23 +244,73 @@ void set_attachment_layouts(std::vector<T_SubpassDescription> &subpass_descripti
...
+}
+
 template <typename T>
-std::vector<T> get_subpass_dependencies(const size_t subpass_count)
+std::vector<T> get_subpass_dependencies(const size_t subpass_count, bool depth_stencil_dependency = false)
```
Comment (asuessenbach) [inline framework/core/render_pass.cpp]: The default argument for `depth_stencil_dependency` is not needed. This function is always (one time!) called with full argument set.

File: framework/core/render_pass.cpp [hunk 3]
```diff
@@ -352,6 +401,11 @@ void RenderPass::create_renderpass(const std::vector<Attachment> &attachments, c
 		}
 	}
 
+	if (attachments.size() != load_store_infos.size())
```
Comment (asuessenbach) [inline framework/core/render_pass.cpp]: If this is required, it should be moved to the top of the function, or maybe into the `RenderPass` constructor, where this function is called.

File: framework/core/render_pass.cpp [hunk 4]
```diff
@@ -438,7 +492,7 @@ void RenderPass::create_renderpass(const std::vector<Attachment> &attachments, c
 		color_output_count.push_back(to_u32(color_attachments[i].size()));
 	}
 
-	const auto &subpass_dependencies = get_subpass_dependencies<T_SubpassDependency>(subpass_count);
+	const auto &subpass_dependencies = get_subpass_dependencies<T_SubpassDependency>(subpass_count, is_depth_a_dependency<T_SubpassDescription, T_AttachmentDescription>(subpass_descriptions, attachment_descriptions));
```
Comment (asuessenbach) [inline framework/core/render_pass.cpp]: I think, there's no need to explicitly list the template arguments for `is_depth_a_dependency`. The compiler should be able to identify them anyways.

**Review by asuessenbach — COMMENTED** [review]
Great fix!
Just a couple of minor issues.

File: framework/core/render_pass.cpp (hunk 1 above)
Comment (JoseEmilio-ARM) [reply framework/core/render_pass.cpp:274]: Thanks! Not exactly the same but I updated the code, let me know what you think

File: framework/core/render_pass.cpp (hunk 2 above)
Comment (JoseEmilio-ARM) [reply framework/core/render_pass.cpp]: Done

File: framework/core/render_pass.cpp (hunk 3 above)
Comment (JoseEmilio-ARM) [reply framework/core/render_pass.cpp]: Done

File: framework/core/render_pass.cpp (hunk 4 above)
Comment (JoseEmilio-ARM) [reply framework/core/render_pass.cpp]: Done

**Review by gary-sweet — APPROVED** [review]

**Review by SaschaWillems — APPROVED** [review]
Can confirm that this also fixes #920 for me 👍🏻

**Review by gpx1000 — APPROVED** [review]

**Comment by marty-johnson59** [comment]
3 approvals - merging
