### PR TITLE
Fix calibrated timestamps

### LINKED ISSUE #1454: Calibrated timestamp samples crashing
While doing PR reviews I noticed that the calibrated timestamps samples crashes on my setup: Windows 11, Nvidia RTX 4070, recent drivers, latest Vulkan SDK.

Before the crash I see the following validation errors:

```
[error] -2001841718 - VUID-VkCalibratedTimestampInfoKHR-timeDomain-parameter: vkGetCalibratedTimestampsEXT(): pTimestampInfos[2].timeDomain (VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT) requires the extensions VK_EXT_present_timing.
The Vulkan spec states: timeDomain must be a valid VkTimeDomainKHR value (https://docs.vulkan.org/spec/latest/chapters/synchronization.html#VUID-VkCalibratedTimestampInfoKHR-timeDomain-parameter)
[error] 867943797 - VUID-VkCalibratedTimestampInfoKHR-timeDomain-12227: vkGetCalibratedTimestampsEXT(): pTimestampInfos[2].timeDomain is VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT but pNext (VkSwapchainCalibratedTimestampInfoEXT::pNext is NULL) does not contain VkSwapchainCalibratedTimestampInfoEXT.
The Vulkan spec states: If timeDomain is VK_TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT or VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT, the pNext chain must include a VkSwapchainCalibratedTimestampInfoEXT structure. (https://docs.vulkan.org/spec/latest/chapters/synchronization.html#VUID-VkCalibratedTimestampInfoKHR-timeDomain-12227)
```

The actual crash happens in the `get_timestamps` function when trying to call `vkGetCalibratedTimestampsEXT`.

This is crashing inside the driver, combined with above validation errors it seems the sample is doing something wrong.

### PR DESCRIPTION
**Pull request by gpx1000**
Add support for additional Vulkan time domains while skipping swapchain-specific domains requiring extra setup

fix the crash in the `calibrated_timestamps` sample reported in issue #1454.

The issue was caused by the sample unconditionally querying and attempting to use all calibrateable time domains returned by the physical device. Specifically, `VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT` and `VK_TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT` require the `VK_EXT_present_timing` extension to be enabled and a `VkSwapchainCalibratedTimestampInfoEXT` structure to be provided in the `pNext` chain of `VkCalibratedTimestampInfoEXT`. Since the sample did not meet these requirements, it triggered validation errors and crashed on hardware supporting these domains (e.g., Nvidia RTX 40 series).

## Description

Please include a summary of the change, new sample or fixed issue. Please also include relevant motivation and context.
Please read the [contribution guidelines](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc)

Fixes #1454 

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

 If this PR contains framework changes:
 - [ ] I did a full batch run using the `batch` command line argument to make sure all samples still work properly

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the readme of the folder that the sample belongs to [e.g. api samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

File: samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp [hunk 1]
```diff
@@ -778,16 +782,23 @@ void CalibratedTimestamps::get_time_domains()
...
-	if (time_domain_count > 0)
-	{
-		for (VkTimeDomainEXT time_domain : time_domains)
+		time_domains.clear();
+		timestamps_info.clear();
+
+		for (VkTimeDomainEXT time_domain : all_time_domains)
 		{
+			// Skip swapchain specific time domains as they require extra setup (VK_EXT_present_timing and pNext)
+			if (time_domain == VK_TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT || time_domain == VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT)
```
Comment (asuessenbach) [inline samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp]: Shouldn't we use a whitelist here, instead of a blacklist, using all the domains we know how to handle right now?
Otherwise some new domain might appear with some upcoming version that also needs additional handling.

**Review by SaschaWillems — CHANGES_REQUESTED** [review]
This does fix my crash, but I'm with Andreas on this. To future proof this, checking for the domains that are known to work would be the better option.

File: samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp [hunk 2]
```diff
@@ -791,8 +791,10 @@ void CalibratedTimestamps::get_time_domains()
 
 		for (VkTimeDomainEXT time_domain : all_time_domains)
 		{
-			// Skip swapchain specific time domains as they require extra setup (VK_EXT_present_timing and pNext)
-			if (time_domain == VK_TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT || time_domain == VK_TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT)
+			if (time_domain != VK_TIME_DOMAIN_DEVICE_EXT &&
+			    time_domain != VK_TIME_DOMAIN_CLOCK_MONOTONIC_EXT &&
+			    time_domain != VK_TIME_DOMAIN_CLOCK_MONOTONIC_RAW_EXT &&
+			    time_domain != VK_TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_EXT)
```
Comment (asuessenbach) [inline samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp:797]: I would have encoded it slightly differently:
```
static const std::set<VkTimeDomainEXT> time_domains_whitelist = {
			VK_TIME_DOMAIN_DEVICE_EXT,
			VK_TIME_DOMAIN_CLOCK_MONOTONIC_EXT,
			VK_TIME_DOMAIN_CLOCK_MONOTONIC_RAW_EXT,
			VK_TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_EXT,
};
if (time_domains_whitelist.contains(time_domain))
{
    time_domains.push_back(time_domain);
    ...
}
```

**Review by asuessenbach — APPROVED** [review]

File: samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp (hunk 2 above)
Comment (gpx1000) [reply samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp:797]: :+1: That would indeed work too.

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Comment by SaschaWillems** [comment]
Merging this, otherwise I won't be able to do batch runs to review PRs.
