### PR TITLE
Expand und update hello triangle (1.0) sample

### LINKED ISSUE #1168: Clean up (and maybe extend) Hello Triangle sample
I'm currently working on a hell triangle sample for Vulkan 1.3 and noticed that our existing hello triangle sample is in dire need of a code cleanup. While it works fine, there are several parts in the code that make it hard to follow. Other parts are unnecessary, variables are named badly and sometimes not even used at all. Also validation layers are not always properly enabled as only parts of the sample also use the debug define to enable them, others don't. Also some of the error messages are plainly wrong and may mislead readers.

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This PR expands and uptates the Vulkan 1.0 hello triangle sample to make it a better starting point for people new to Vulkan:

- Use C++ 20 designated initializers
- Use a vertex buffer instead of hard coding vertices in the vertex shader (using VMA)
- Use offline compiled shaders (duplicated to a dedicated folder, so other samples that use the same shaders aren't affected)
- Adds hlsl and slang shaders (can be selected via the --shading-language command line argument)

Once this is merged, the same hlsl and slang shaders (and selection) can also be added to the hello triangle 1.3 sample.

Fixes #1168
Refs #1107
Refs #1110
Refs #1014

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

### CODE REVIEW

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 1]
```diff
@@ -685,7 +685,7 @@ void HelloTriangle::init_render_pass()
  * @param path The path for the shader (relative to the assets directory).
  * @returns A VkShaderModule handle. Aborts execution if shader creation fails.
  */
-VkShaderModule HelloTriangle::load_shader_module(const char *path)
+VkShaderModule HelloTriangle::load_shader_module(const std::string path)
```
Comment (gpx1000) [inline samples/api/hello_triangle/hello_triangle.cpp]: might add a & in there; this copies the path every call needlessly.

Comment (SaschaWillems) [reply samples/api/hello_triangle/hello_triangle.cpp]: Good catch. Sometimes MSVC hints you at that, and sometimes it doesn't ^^

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 2]
```diff
@@ -338,21 +340,80 @@ void HelloTriangle::init_device()
...
 
 	vkGetDeviceQueue(context.device, context.graphics_queue_index, 0, &context.queue);
+
+	// This sample uses the Vulkan Memory Alloctor (VMA), which needs to be set up
+	VmaVulkanFunctions vma_vulkan_func{
+	    .vkGetInstanceProcAddr = vkGetInstanceProcAddr,
+	    .vkGetDeviceProcAddr   = vkGetDeviceProcAddr};
+
+	VmaAllocatorCreateInfo allocator_info{
+	    .physicalDevice   = static_cast<VkPhysicalDevice>(context.gpu),
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: The `context.gpu` is a `VkPhysicalDevice`. No need to `static_cast` here.

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 3]
```diff
@@ -338,21 +340,80 @@ void HelloTriangle::init_device()
...
+	    .device           = static_cast<VkDevice>(context.device),
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: The `context.device` is a `VkDevice`. No need to `static_cast` here.

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 4]
```diff
@@ -338,21 +340,80 @@ void HelloTriangle::init_device()
...
+	    .pVulkanFunctions = &vma_vulkan_func,
+	    .instance         = static_cast<VkInstance>(context.instance)};
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: The `context.instance` is a `VkInstance`. No need to `static_cast` here.

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 5]
```diff
@@ -338,21 +340,80 @@ void HelloTriangle::init_device()
...
+	    .usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT};
+
+	// We use the Vulkan Memory Allocator to find a memory type that can be written and mapped from the host
+	// On most setups this will return a memory type that resides in VRAM and is accessible from the host
+	VmaAllocationCreateInfo buffer_alloc_ci{
+	    .flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_MAPPED_BIT,
+	    .usage = VMA_MEMORY_USAGE_AUTO};
+
+	VmaAllocationInfo buffer_alloc_info{};
+	vmaCreateBuffer(context.vma_allocator, &buffer_info, &buffer_alloc_ci, reinterpret_cast<VkBuffer *>(&vertex_buffer), &vertex_buffer_allocation, &buffer_alloc_info);
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: The `vertex_buffer` is a `VkBuffer`. No need to `reinterpret_cast` here.

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 6]
```diff
@@ -543,17 +607,12 @@ void HelloTriangle::init_swapchain()
...
-		view_info.components.r                = VK_COMPONENT_SWIZZLE_R;
-		view_info.components.g                = VK_COMPONENT_SWIZZLE_G;
-		view_info.components.b                = VK_COMPONENT_SWIZZLE_B;
-		view_info.components.a                = VK_COMPONENT_SWIZZLE_A;
+		VkImageViewCreateInfo view_info{
+		    .sType            = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
+		    .image            = swapchain_images[i],
+		    .viewType         = VK_IMAGE_VIEW_TYPE_2D,
+		    .format           = context.swapchain_dimensions.format,
+		    .subresourceRange = {.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT, .baseMipLevel = 0, .levelCount = 1, .baseArrayLayer = 0, .layerCount = 1}};
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp:615]: It is correct to not explicitly set the `view_info.components`, as they are set to `0` by default, which actually is `VK_COMPONENT_SWIZZLE_IDENTITY`.
But was that skipped intentionally or by accident?

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 7]
```diff
@@ -594,67 +646,55 @@ void HelloTriangle::init_render_pass()
...
  */
-VkShaderModule HelloTriangle::load_shader_module(const char *path)
+VkShaderModule HelloTriangle::load_shader_module(const std::string &path)
 {
-	vkb::GLSLCompiler glsl_compiler;
-
-	auto buffer = vkb::fs::read_shader_binary(path);
+	auto                  buffer = vkb::fs::read_shader_binary(path);
+	std::vector<uint32_t> spirv  = std::vector<uint32_t>(reinterpret_cast<uint32_t *>(buffer.data()),
+                                                        reinterpret_cast<uint32_t *>(buffer.data()) + buffer.size() / sizeof(uint32_t));
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp:692]: Is the size of buffer always a multiple of 4 (`sizeof(uint32_t)`)?
Maybe add an assertion on it to express what's expected here.

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 8]
```diff
@@ -669,78 +709,123 @@ void HelloTriangle::init_pipeline()
...
 
 	// Specify that these states will be dynamic, i.e. not part of pipeline state object.
 	std::array<VkDynamicState, 2> dynamics{VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
 
-	VkPipelineDynamicStateCreateInfo dynamic{VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};
-	dynamic.pDynamicStates    = dynamics.data();
-	dynamic.dynamicStateCount = vkb::to_u32(dynamics.size());
+	VkPipelineDynamicStateCreateInfo dynamic{
+	    .sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
+	    .dynamicStateCount = vkb::to_u32(dynamics.size()),
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: Do you have some rule, when you're using `vkb::to_u32` and when `static_cast<uint32_t>`?

File: samples/api/hello_triangle/hello_triangle.cpp [hunk 9]
```diff
@@ -896,12 +987,13 @@ void HelloTriangle::render_triangle(uint32_t swapchain_index)
...
-	present.pImageIndices      = &index;
-	present.waitSemaphoreCount = 1;
-	present.pWaitSemaphores    = &context.per_frame[index].swapchain_release_semaphore;
+	VkPresentInfoKHR present{
+	    .sType              = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
+	    .waitSemaphoreCount = 1,
+	    .swapchainCount     = 1,
+	    .pSwapchains        = &context.swapchain,
+	    .pImageIndices      = &index};
+	present.pWaitSemaphores = &context.per_frame[index].swapchain_release_semaphore;
```
Comment (asuessenbach) [inline samples/api/hello_triangle/hello_triangle.cpp]: Why do you keep the `pWaitSemaphores` out of the initializer list?

**Review by asuessenbach — COMMENTED** [review]
Just some minor issues...

File: samples/api/hello_triangle/hello_triangle.cpp (hunk 7 above)
Comment (SaschaWillems) [reply samples/api/hello_triangle/hello_triangle.cpp:692]: I did copy this from the framework's shader loading code, so I guess it's correct.

File: samples/api/hello_triangle/hello_triangle.cpp (hunk 8 above)
Comment (SaschaWillems) [reply samples/api/hello_triangle/hello_triangle.cpp]: Nope. I'm not sure about this, but the sample was already using vkb::to_u32 in here, which is not the same as a static cast. But tbh. I don't think that anything in the sample requires the logic of to_u32, so will replace with casts.

File: samples/api/hello_triangle/hello_triangle.cpp (hunk 9 above)
Comment (SaschaWillems) [reply samples/api/hello_triangle/hello_triangle.cpp]: That was unintentional.

File: samples/api/hello_triangle/hello_triangle.cpp (hunk 6 above)
Comment (SaschaWillems) [reply samples/api/hello_triangle/hello_triangle.cpp:615]: Afaik that is correct, and something we did in other samples too.

**Review by asuessenbach — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Comment by marty-johnson59** [comment]
3 approvals - merging
